### ISSUE TITLE
Empty Blank Page Load Time

### ISSUE THREAD

**Issue by gitti0** [alex-vv/page-load-time#31]
I have Empty Blank Page Load Time in Firefox.

My system is Windows10, Firefox 68ESR, 4k monitor and Intel integrated card.

I tried on another system again Wndows 10, Firefox 68ESR but not 4k display and the navigation timmig is working properly.

Both setups are with clean Firefox profile and the only extension is the page load time.

There is indentical closed issue but in Chrome #30 .

![PageLoadTime](https://user-images.githubusercontent.com/72917708/96260262-baf4c500-0fb6-11eb-8a5b-6c1305f45dfc.jpg)

**Comment by alex-vv** [comment]
I could not reproduce it on Windows 10 and Firefox 68 ESR. Can you try to check for any errors using extension debug?

For that go to Add-ons page click gear icon and select Debug Add-ons. Then select Page load time extension and click Debug button (or Inspect depending on Firefox version). It will open a debug window, select a Console tab there. Then go to some website and try opening the extension popup. Check back if any errors appeared in debug window. If there are some please post it in this ticket.

**Comment by gitti0** [comment]
I have the following errors in the Console tab, when the page is fully loaded and click on the PageLoadTime icon:

"The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol. popup.html"

"TypeError: t is undefined popup.js:18:5"

"TypeError: Argument 1 of PrecompiledScript.executeInGlobal is not an object. ExtensionContent.jsm:554:25"

"Promise resolved after context unloaded
settings.js:442
    <anonymous> moz-extension://2dceb0fc-6a14-412e-ba22-0f45f689a616/lib/settings.js:442"

"Promise resolved after context unloaded
content.js:437
    updatePreferences moz-extension://f1ae7829-ee70-4cd2-a2f1-9a804a2cddff/content.js:437"

**Comment by gitti0** [comment]
@alex-vv, you could consider to add "<meta charset="utf-8">" in the popup.html

That should fix the problem.

**Comment by alex-vv** [comment]
> @alex-vv, you could consider to add `<meta charset="utf-8">` in the popup.html
> 
> That should fix the problem.

I added it here https://github.com/alex-vv/page-load-time/commit/7bd37a988f213e29e399b15daa071dc979c4536d but I don't think that this problem happens because of an encoding, as the real error is "TypeError: t is undefined popup.js:18:5"

I am going to investigate it more, meanwhile you can check the current master.

**Comment by alex-vv** [comment]
I pushed another commit which could probably solve the issue. I could not verify it as I cannot reproduce the original problem. 

@gitti0 can you try the latest change to see if it fixes the issue for you?

**Comment by gitti0** [comment]
I tried the latest master in the same scenario and the values are displayed correctly.

![pageloadtime_new](https://user-images.githubusercontent.com/72917708/97293837-1dff1b00-1845-11eb-8aa1-da7e8ef0811c.jpg)

**Comment by alex-vv** [comment]
good, then I will close this and release the fix in the new version

**Comment by gitti0** [comment]
@alex-vv apologies but the bug is still there. I think this time I could point you in better direction. I made further tests, because the issue is still present.

Please follow my steps in order to reproduce it:
1. Start Firefox with clean profile. Instal the page load extension and give the appropriate permissions, the extension to run in private windows. Don't open any pages.
2. Open private window and load e.g. facebook.com
3. Open the page load extension with the table values.

I tried to represend the bug and I could confirm, how the bug is on every system in my tests but only in private windows.
I made the tests using Firefox ESR 68.12 and Firefox ESR 78.4 on Windows 10.

**Comment by alex-vv** [comment]
thanks, I manage to reproduce it and pushed a fix which solves it for me. Can you try the latest master once more?

**Comment by gitti0** [comment]
It's working for me as well. Thank you.

I am closing the issue, because of the working solution.
